# Generated by Django 4.2 on 2025-02-10 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customproductdesignerapp', '0002_rename_user_users'),
        ('adminapp', '0010_remove_color_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Designimages/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.color')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customproductdesignerapp.users')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.products')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.size')),
            ],
        ),
    ]
