# Generated by Django 4.2 on 2025-02-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customproductdesignerapp', '0002_rename_user_users'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Designimages/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customproductdesignerapp.users')),
            ],
        ),
    ]
