# Generated by Django 4.2 on 2025-02-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='requested_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.design_request')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.template')),
            ],
        ),
    ]
