# Generated by Django 4.2 on 2025-02-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_requested_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_request',
            name='add_to_template',
            field=models.BooleanField(default=False),
        ),
    ]
