# Generated by Django 4.2 on 2025-02-11 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_design_request_add_to_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('gift_note', models.CharField(blank=True, max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.design_request')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('hname', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('pin', models.CharField(max_length=6)),
                ('phonenumber', models.CharField(max_length=15)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.design_request')),
            ],
        ),
    ]
