# Generated by Django 4.2 on 2025-03-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design_request',
            old_name='description',
            new_name='requestdescription',
        ),
    ]
