# Generated by Django 4.2 on 2025-03-17 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_description_design_request_requestdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phonenumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', message='Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Pin code must be exactly 6 digits.')]),
        ),
    ]
