# Generated by Django 4.2 on 2025-03-17 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_address_phonenumber_alter_address_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phonenumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid phone number.')]),
        ),
    ]
