# Generated by Django 4.2 on 2025-03-17 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customproductdesignerapp', '0002_rename_user_users'),
        ('customer', '0010_alter_address_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customproductdesignerapp.users')),
            ],
        ),
    ]
