# Generated by Django 4.2 on 2025-03-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customproductdesignerapp', '0002_rename_user_users'),
        ('customer', '0011_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_received', to='customproductdesignerapp.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_sent', to='customproductdesignerapp.users'),
        ),
    ]
