# Generated by Django 4.2 on 2025-03-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_wallet_receiver_alter_wallet_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='receiver',
        ),
        migrations.AddField(
            model_name='wallet',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.design_request'),
            preserve_default=False,
        ),
    ]
