# Generated by Django 4.2 on 2025-04-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_wallet_receiver_wallet_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercolor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color_image', models.ImageField(blank=True, null=True, upload_to='Userimages/')),
            ],
        ),
    ]
