# Generated by Django 5.1.5 on 2025-01-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='size',
            new_name='name',
        ),
    ]
