# Generated by Django 5.1.5 on 2025-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_category_color_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorname', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_images/')),
            ],
        ),
    ]
