# Generated by Django 5.1.5 on 2025-01-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_images/')),
            ],
        ),
    ]
