# Generated by Django 4.2 on 2025-02-04 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customproductdesignerapp', '0002_rename_user_users'),
        ('adminapp', '0007_remove_products_category_id_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='designer_photos/')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customproductdesignerapp.logins')),
            ],
        ),
    ]
