# Generated by Django 4.2 on 2025-02-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_products_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='image',
        ),
    ]
