# Generated by Django 4.2 on 2025-03-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_gift_address'),
        ('adminapp', '0010_remove_color_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyDesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.design_request')),
            ],
        ),
    ]
