# Generated by Django 4.2 on 2025-03-17 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_notifydesignrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifydesignrequest',
            name='designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.designers'),
            preserve_default=False,
        ),
    ]
