# Generated by Django 4.2 on 2025-04-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_notifydesignrequest_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='freetemplate/')),
            ],
        ),
    ]
