# Generated by Django 4.2 on 2025-04-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_freetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Designimages/'),
        ),
    ]
