# Generated by Django 4.2 on 2025-04-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_alter_freetemplate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifydesignrequest',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
