# Generated by Django 4.2 on 2025-04-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_notifydesignrequest_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifydesignrequest',
            name='credited_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
