# Generated by Django 5.1.5 on 2025-02-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customproductdesignerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
    ]
